kind: KongUpstream
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: httproute.default.httproute-quote.0.0
spec:
  controlPlaneRef:
    konnectNamespacedRef:
      name: cp-zonkey
    type: konnectNamespacedRef
  name: httproute.default.httproute-quote.0.0
