kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: api-konnect
spec:
  type: token
  token: "kpat_XXXXX"
  serverURL: eu.api.konghq.tech
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: cp-zonkey
spec:
  createControlPlaneRequest:
    name: zonkey
  konnect:
    authRef:
      name: api-konnect
