apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 2
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: quay.io/fgiudici/echo:v0.3.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2
spec:
  selector:
    matchLabels:
      app: echo2
  replicas: 1
  template:
    metadata:
      labels:
        app: echo2
    spec:
      containers:
        - name: echo
          image: quay.io/fgiudici/echo:v0.3.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo2
  labels:
    app: echo2
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    app: echo2
