kind: KongTarget
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: httproute.default.httproute-quote.0.0.0
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      blockOwnerDeletion: true
      kind: HTTPRoute
      name: httproute-quote
spec:
  target: quotaday.default.svc.cluster.local:8080
  upstreamRef:
    name: httproute.default.httproute-quote.0.0
  weight: 2
---
kind: KongTarget
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: httproute.default.httproute-quote.0.0.1
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      blockOwnerDeletion: true
      kind: HTTPRoute
      name: httproute-quote
spec:
  target: quotaday2.default.svc.cluster.local:8088
  upstreamRef:
    name: httproute.default.httproute-quote.0.0
  weight: 4

