kind: KonnectExtension
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: extension
spec:
  clientAuth:
    certificateSecret:
      provisioning: Automatic
  konnect:
    controlPlane:
      ref:
        type: konnectNamespacedRef
        konnectNamespacedRef:
          name: cp-konnect
