apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dp
spec:
  extensions:
  - kind: KonnectExtension
    name: extension
    group: konnect.konghq.com
  deployment:
    podTemplateSpec:
      spec:
        containers:
        - name: proxy
          image: kong/kong-gateway:3.11

